### ISSUE TITLE
Elasticsearch 7.x versions support

### ISSUE THREAD

**Issue by haileypark-kr** [elastic/xk6-output-elasticsearch#29]
I'm trying to connect xk6-output-elasticsearch with elasticsearch 7.x versions but I don't think that this plugin supports ES 7 versions.

I ran Elasticsearch-oss 7.10.2 version and Opensearch 2.8.0 version (compatible with Elasticsearch 7.x versions) on docker containers.
- docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
- opensearchproject/opensearch:2.8.0

When connected to Elasticsearch-oss 7.10.2 version and Opensearch  2.8.0 version, both exited with an error like below:
```
 docker run --rm --network docker-data_k6 -e K6_ELASTICSEARCH_URL=http://opensearch:9200 -i xk6-output-elasticsearch run -o output-elasticsearch --tag testid=$(date "+%Y%m%d-%H%M%S")  - <k6-scripts/script.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

time="2024-03-22T01:17:07Z" level=info msg="Elasticsearch: configuring output"

Init      [   0% ]
default   [   0% ]
time="2024-03-22T01:17:07Z" level=error msg="could not create the 'output-elasticsearch' output: the client noticed that the server is not Elasticsearch and we do not support this unknown product"
```

To reproduce my case, I attach a `docker-compose.yml` file for Opensearch 2.8.0.
```yml
version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:2.8.0
    container_name: opensearch
    environment:
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "discovery.type=single-node"
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 19200:9200 # REST API
      - 19600:9600 # Performance Analyzer
    networks:
      - k6
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.8.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - k6

volumes:
  opensearch-data:

networks:
  k6:
```
